project:
    title: Detecting Bots on Reddit
    output-dir: docs
title: Detecting Bots on Reddit
subtitle: Computational Social Science
author: Matteo Mazzarelli
date: today
date-format: long
format:
    pdf:
        number-sections: true
        include-in-header: extra/preamble.tex
        fontsize: 12pt
        linestretch: 1
        geometry:
            - top=1.5cm
            - bottom=3cm
            - hmargin=2.5cm
        link-citations: true
        keep-tex: true
        pdf-engine: latexmk
        pdf-engine-opts: 
            - "-lualatex"
            - "-f"
            - "-gg"
            # - "-interaction=nonstopmode"
execute:
    cache: true
    # echo: false
    warning: false
bibliography: extra/references.bib
csl: extra/apa7-numeric-superscript-brackets-nocommas.csl
# nocite: |
#     @*
